# Generated by Django 3.0.6 on 2020-05-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='id_osoba',
            field=models.ForeignKey(db_column='id_osoba', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Osoba'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='iduzytkownik',
            field=models.AutoField(db_column='idUzytkownik', primary_key=True, serialize=False),
        ),
    ]
