# Generated by Django 3.0.6 on 2020-05-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200521_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='id_osoba',
            field=models.OneToOneField(db_column='id_osoba', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Osoba'),
        ),
    ]
