# Generated by Django 3.0.6 on 2020-06-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200604_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytanie',
            name='tresc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sciezkapytan',
            name='id_diagnoza_jesli_nie',
            field=models.OneToOneField(blank=True, db_column='id_diagnoza_jesli_nie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_diagnoza_jesli_nie', to='user.Diagnoza'),
        ),
        migrations.AlterField(
            model_name='sciezkapytan',
            name='id_diagnoza_jesli_tak',
            field=models.OneToOneField(blank=True, db_column='id_diagnoza_jesli_tak', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_diagnoza_jesli_tak', to='user.Diagnoza'),
        ),
        migrations.AlterField(
            model_name='sciezkapytan',
            name='id_next_pytanie_jesli_nie',
            field=models.OneToOneField(blank=True, db_column='id_next_pytanie_jesli_nie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_next_pytanie_jesli_nie', to='user.Pytanie'),
        ),
        migrations.AlterField(
            model_name='sciezkapytan',
            name='id_next_pytanie_jesli_tak',
            field=models.OneToOneField(blank=True, db_column='id_next_pytanie_jesli_tak', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_next_pytanie_jesli_tak', to='user.Pytanie'),
        ),
        migrations.AlterField(
            model_name='sciezkapytan',
            name='id_pytanie',
            field=models.OneToOneField(blank=True, db_column='id_pytanie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_pytanie', to='user.Pytanie'),
        ),
        migrations.AlterField(
            model_name='sciezkapytan',
            name='id_rodzaj_zdarzenia',
            field=models.OneToOneField(blank=True, db_column='id_rodzaj_zdarzenia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.RodzajZdarzenia'),
        ),
    ]
