# Generated by Django 3.0.6 on 2020-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200604_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodzajincydentu',
            name='nazwa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
